### PR TITLE
Add questionnaire documentation

### PR DESCRIPTION
**Pull request by amageh**
The documentation can be accessed [here](https://liss-questionnaires.readthedocs.io/en/create-docs/index.html). The .rst-files in the folder `docs/source/wave-1/english` can be generated automatically using the notebook in `create-documentation` in the root of this repository. We can thus easily add Dutch/German versions of the questions or future waves if we have suitable description tables for the questions.  

To-Do's/Questions:

* [x] Update .rst-files for question documentation with latest description table. (in progress)
* [x] Add text to title page. -> What info should the title page contain, should we link to the dashboard?
* [x] Should we add more information to the questions like variable names, GESIS indicator, etc. ?

### CODE REVIEW

**Review by roecla — APPROVED** [review]
## On the output: 
This looks very good overall already! 
I have some suggestions that I think would make it look even more professional, but most of them are minor: 

- Questionnaire Example looks like the whole questionnaire to me.
- In the Questions it would be great to have the nested levels of topics and groups to have more structure. The index would look much better like that, too.
- The questions are italic at the moment. I think normal font style would look better
- maybe we can add the (new) variable name to each question? I think that would be nice
- for example in `Appropriateness of Policies` there is an empty row. I would remove that. 
- overall you could probably remove quite a few lines from the tables. (in the spirit of [Janos' animation from this morning](http://www.randalolson.com/wp-content/uploads/data-ink.gif))
- for the work adjustments the routing is missing. This is a problem of the description table but here it really shows. Not sure how to best handle it, though. Let's discuss it on Zulip.

I have not looked at the code yet. If you wish I'll do that later.

**Comment by hmgaudecker** [comment]
Thanks for all your work! I hope i will be able to have a look tonight.

As for the routing (and other stuff), please have a look at the final questionnaire in Dutch that I just uploaded https://covid-19-impact-lab.readthedocs.io/en/latest/datasets.html

**Comment by hmgaudecker** [comment]
@amageh  I just had a brief look, **very** nice! Let me comment on two things that come to my mind:
* Would it be hard to do two versions? One in the order of appearance, one in the order of groups? If you have one file per question and can just have them appear twice in the table of contents, that would be trivial. Never tried that, though. References would probably be messed up, maybe we can think of a little pre-processor there (some jinja2-magic by @tobiasraabe, maybe ?)
* Would it be tough to include the screenshots on the pages themselves?
The broad thing is great, though, I will have another look once the new grouping of variables is implemented (as discussed with @roecla in the morning), else it is hard to focus.

**Comment by hmgaudecker** [comment]
I just realised these are in parts much shortened versions of the questions. 

E.g., the 1000 € question misses almost all the relevant context. It does not become clear at all that groceries are only to be included if people have no other way of paying for them. This is also why it is way too complex to show up in the public dashboard.

Maybe in the end it is better to stick to the question text as opposed to the dashboard text?

**Comment by amageh** [comment]
> I just realised these are in parts much shortened versions of the questions.
> 
> E.g., the 1000 € question misses almost all the relevant context. It does not become clear at all that groceries are only to be included if people have no other way of paying for them. This is also why it is way too complex to show up in the public dashboard.
> 
> Maybe in the end it is better to stick to the question text as opposed to the dashboard text?

@hmgaudecker Yes I agree, I have been holding off on touching the description table since it would have been nice to hit two birds with one stone by using the same table for both the dashboard and the documentation, but it's probably better to adjust it in order to reflect the questionnaire more closely. 

I will be editing the table then, this will make it easier to implement some of the other things you touched on as well. I'll tag you again when I am done. :-).

**Comment by amageh** [comment]
I have updated the [documentation](https://liss-questionnaires.readthedocs.io/en/create-docs/wave-1/index.html) to reflect the questionnaire more closely. There are still some bugs and things I need to fix, namely:

- Some screenshots need to be added.
- I plan on adding a note on routing to each question so it is clear if only a subgroup of individuals were asked to answer a question.
- Some links aren't working properly yet.
- I know some tables are formatted a bit weirdly, I will try to fix that, too.
- The TOC tree is too long. 

@hmgaudecker It would be great if you could take a look again and let me know whether the general structure is acceptable!

**Comment by amageh** [comment]
I have implemented the edits we discussed. I am merging this pull request and will create a new one for wave 2 tomorrow.

**Pull request merged**
